brown-ccv/ccv-website-content

services/file-storage-and-transfer/index.yml
This PR adds the two storage services that the Library provides to the storage finder app.
=> added the two library storage services

.github/workflows/prod_deply_on_merge.yml
and we won't know if it works until we merge (twice)
=> ci: add workflow to dispatch full prod build

services/file-storage-and-transfer/index.yml
add a default option (needed for storage clean up PR on website)
=> feat: add default answer for storage

storage-tool.yml
and I guess this is why schemas are useful... but we never did one for this one
=> fix: add  missing default answer

about/oit.md
This is a baby PR that adds an OIT section to our `About` page. Kudos to @mcmcgrath13 for the help on the content!
=> feat: add oit section to about page

our-work/software/cave-painting.yml
I'd like to add cave-painting  as one of the projects we have worked at.
=> Add cave painting to software

about/people.yml
Various small corrections in Bio texts (no content changes)
=> Fix bio spelling

our-work/collaborations/riddc.yml, our-work/collaborations/wilhelmus.yml, schemas/collaborations.yml
I added the Ice Floe collaboration, added myself to the RIDDC collab, and added a tag for `climate-science`
=> feat: add Ice Floe collab and update RIDDC

about/facilities.md, services/computing/oscar.md
This pull request removes the System information table under Services->Computing->Oscar and points to the frequently updated page in the Oscar docs.
The facilities statement regarding Oscar is also updated under About-> Facilities Statement.
=> Updating Oscar System Info

about/people.yml
=> Fixed typo

our-work/workshops-and-talks/remote_renderer, schemas/workshops-and-talks.yml
- Added yml for remote rendering workshop
- Added visualization category
=> Feature dscov remote render

about/teams.md
=> chore: Mary is out, Brad wasn't in there

our-work/workshops-and-talks/introduction-to-python.yml
=> feat: introduction to python

services/computing/stronghold.md
I changed Stronghold Environment Request Form (SERF) link to the new link.
=> Update stronghold.md (Stronghold Environment Request Form link)

storage-tool.yml
This is a baby PR that makes the link to the Data Risk Classification a bit more prominent. This PR is a response to a request from Greg on the ISG team.
=> chore: update the text of the risk classiciation system in the storage app

our-work/collaborations/bnc.yml, our-work/collaborations/braingate.yml, our-work/collaborations/serre.yml, our-work/collaborations/tpl.yml
now alphabetical across all cards
=> chore: reorder buttons to be consistent across cards

about/people.yml
=> fix: ashley's subteam typo

about/people.yml
=> feat: Add Rob Gemma's bio

rates.md
=> edit_rates

rates.md
**Before:**
Rdata: $100 / Terabyte / year
Stronghold Storage: $100 / Terabyte / Year
Campus File Storage (replicated): $100 / Terabyte / Year
Campus File Storage (non-replicated): $50 / Terabyte / Year
**After:**
Rdata: $100 / Terabyte / Year ($8.3 / Terabyte / Month)
Stronghold Storage: $100 / Terabyte / Year ($8.3 / Terabyte / Month)
Campus File Storage (replicated): $100 / Terabyte / Year ($8.3 / Terabyte / Month)
Campus File Storage (non-replicated): $50 / Terabyte / Year ($4.2 / Terabyte / Month)
=> edited Research Data Storage

rates.md
Changed: "charge a quarterly fee" to "monthly".
=> change quarterly to monthly

services/file-storage-and-transfer/brown-storage.md, storage-tool.yml
1. Adds "Request Storage" link to the storage section
2. Updates descriptions and matrix comparisons
=> chore: update storage descriptions

services/file-storage-and-transfer/brown-storage.md
> Create a link/button on the main page for (next to compare storage options)
> Request Storage
> Quota Increase requests
> For both requests URL JSM portal link: https://brown.atlassian.net/servicedesk/customer/portal/16
=> feat: request storage and quota increase buttons

services/file-storage-and-transfer/brown-storage.md
=> feat: Add new definitions to storage landing page

services/computing/virtual-machines.md
This is a tiny PR that updates the form used to request virtual machines.
=> feat: update link for requesting a virtual machine

our-work/software/cave-painting.yml, our-work/software/vr-volume-viewer.yml
The details of draw on air and volume viewer don't show up. Camilo's name need to match the one listed in people.yml
=> [Maint] Fix Camilo software details 
